insert into city values ('Colombo 1', 'main');
insert into city values ('Colombo 10', 'main');
insert into city values ('Colombo 11', 'main');
insert into city values ('Colombo 12', 'main');
insert into city values ('Colombo 13', 'main');
insert into city values ('Colombo 14', 'main');
insert into city values ('Colombo 15', 'main');
insert into city values ('Colombo 2', 'main');
insert into city values ('Colombo 3', 'main');
insert into city values ('Colombo 4', 'main');
insert into city values ('Colombo 5', 'main');
insert into city values ('Colombo 6', 'main');
insert into city values ('Colombo 7', 'main');
insert into city values ('Colombo 8', 'main');
insert into city values ('Colombo 9', 'main');
insert into city values ('Kalutara South', 'main');
insert into city values ('Kalutara North', 'main');
insert into city values ('Trincomalee', 'main');

insert into city values ('Vavuniya', 'secondary');
insert into city values ('Horana', 'secondary');
insert into city values ('Panadura', 'secondary');
insert into city values ('Matugama', 'secondary');
insert into city values ('Bandaragama', 'secondary');
insert into city values ('Alutgama', 'secondary');
insert into city values ('Beruwala', 'secondary');
insert into city values ('Ingiriya', 'secondary');
insert into city values ('Wadduwa', 'secondary');
insert into city values ('Mullativu ', 'secondary');
insert into city values ('Matara', 'secondary');
insert into city values ('Akuressa', 'secondary');
insert into city values ('Weligama', 'secondary');
insert into city values ('Dikwella', 'secondary');
insert into city values ('Hakmana', 'secondary');
insert into city values ('Deniyaya', 'secondary');
insert into city values ('Kamburugamuwa', 'secondary');
insert into city values ('Kamburupitiya', 'secondary');
insert into city values ('Kekanadurra', 'secondary');
insert into city values ('Anuradhapura', 'secondary');
insert into city values ('Kekirawa', 'secondary');
insert into city values ('Tambuttegama', 'secondary');
insert into city values ('Medawachchiya', 'secondary');
insert into city values ('Eppawala', 'secondary');
insert into city values ('Galenbindunuwewa', 'secondary');
insert into city values ('Galnewa', 'secondary');
insert into city values ('Habarana', 'secondary');
insert into city values ('Mihintale', 'secondary');
insert into city values ('Nochchiyagama', 'secondary');
insert into city values ('Talawa', 'secondary');
insert into city values ('Kinniya', 'secondary');
insert into city values ('Galle', 'secondary');
insert into city values ('Ambalangoda', 'secondary');
insert into city values ('Elpitiya', 'secondary');
insert into city values ('Hikkaduwa', 'secondary');
insert into city values ('Baddegama', 'secondary');
insert into city values ('Ahangama', 'secondary');
insert into city values ('Batapola', 'secondary');
insert into city values ('Bentota', 'secondary');
insert into city values ('Karapitiya', 'secondary');
insert into city values ('Batticaloa', 'secondary');
insert into city values ('Matale', 'secondary');
insert into city values ('Dambulla', 'secondary');
insert into city values ('Galewela', 'secondary');
insert into city values ('Ukuwela', 'secondary');
insert into city values ('Rattota', 'secondary');
insert into city values ('Palapathwela', 'secondary');
insert into city values ('Sigiriya', 'secondary');
insert into city values ('Yatawatta', 'secondary');
insert into city values ('Moneragala', 'secondary');
insert into city values ('Buttala', 'secondary');
insert into city values ('Wellawaya', 'secondary');
insert into city values ('Bibile', 'secondary');
insert into city values ('Kataragama', 'secondary');
insert into city values ('Polonnaruwa', 'secondary');
insert into city values ('Hingurakgoda', 'secondary');
insert into city values ('Kaduruwela', 'secondary');
insert into city values ('Medirigiriya', 'secondary');
insert into city values ('Kilinochchi', 'secondary');
insert into city values ('Kandy', 'secondary');
insert into city values ('Katugastota', 'secondary');
insert into city values ('Gampola', 'secondary');
insert into city values ('Peradeniya', 'secondary');
insert into city values ('Kundasale', 'secondary');
insert into city values ('Akurana', 'secondary');
insert into city values ('Ampitiya', 'secondary');
insert into city values ('Digana', 'secondary');
insert into city values ('Galagedara', 'secondary');
insert into city values ('Gelioya', 'secondary');
insert into city values ('Kadugannawa', 'secondary');
insert into city values ('Madawala Bazaar', 'secondary');
insert into city values ('Nawalapitiya', 'secondary');
insert into city values ('Pilimatalawa', 'secondary');
insert into city values ('Wattegama', 'secondary');
insert into city values ('Ratnapura', 'secondary');
insert into city values ('Embilipitiya', 'secondary');
insert into city values ('Balangoda', 'secondary');
insert into city values ('Pelmadulla', 'secondary');
insert into city values ('Eheliyagoda', 'secondary');
insert into city values ('Kuruwita', 'secondary');
insert into city values ('Ampara', 'secondary');
insert into city values ('Akkarepattu', 'secondary');
insert into city values ('Kalmunai', 'secondary');
insert into city values ('Sainthamaruthu', 'secondary');
insert into city values ('Jaffna', 'secondary');
insert into city values ('Nallur', 'secondary');
insert into city values ('Chavakachcheri', 'secondary');
insert into city values ('Kurunegala', 'secondary');
insert into city values ('Kuliyapitiya', 'secondary');
insert into city values ('Narammala', 'secondary');
insert into city values ('Pannala', 'secondary');
insert into city values ('Mawathagama', 'secondary');
insert into city values ('Alawwa', 'secondary');
insert into city values ('Bingiriya', 'secondary');
insert into city values ('Galgamuwa', 'secondary');
insert into city values ('Giriulla', 'secondary');
insert into city values ('Hettipola', 'secondary');
insert into city values ('Ibbagamuwa', 'secondary');
insert into city values ('Nikaweratiya', 'secondary');
insert into city values ('Polgahawela', 'secondary');
insert into city values ('Wariyapola', 'secondary');
insert into city values ('Tangalla', 'secondary');
insert into city values ('Beliatta', 'secondary');
insert into city values ('Tissamaharama', 'secondary');
insert into city values ('Hambantota', 'secondary');
insert into city values ('Ambalantota', 'secondary');
insert into city values ('Nuwara Eliya', 'secondary');
insert into city values ('Hatton', 'secondary');
insert into city values ('Ginigathena', 'secondary');
insert into city values ('Madulla', 'secondary');
insert into city values ('Chilaw', 'secondary');
insert into city values ('Wennappuwa', 'secondary');
insert into city values ('Puttalam', 'secondary');
insert into city values ('Nattandiya', 'secondary');
insert into city values ('Marawila', 'secondary');
insert into city values ('Dankotuwa', 'secondary');
insert into city values ('Kegalle', 'secondary');
insert into city values ('Mawanella', 'secondary');
insert into city values ('Warakapola', 'secondary');
insert into city values ('Rambukkana', 'secondary');
insert into city values ('Ruwanwella', 'secondary');
insert into city values ('Dehiowita', 'secondary');
insert into city values ('Deraniyagala', 'secondary');
insert into city values ('Galigamuwa', 'secondary');
insert into city values ('Kitulgala', 'secondary');
insert into city values ('Yatiyantota', 'secondary');
insert into city values ('Badulla', 'secondary');
insert into city values ('Bandarawela', 'secondary');
insert into city values ('Welimada', 'secondary');
insert into city values ('Mahiyanganaya', 'secondary');
insert into city values ('Hali Ela', 'secondary');
insert into city values ('Diyatalawa', 'secondary');
insert into city values ('Ella', 'secondary');
insert into city values ('Haputale', 'secondary');
insert into city values ('Passara', 'secondary');
insert into city values ('Rajagiriya', 'secondary');
insert into city values ('Dehiwala', 'secondary');
insert into city values ('Nugegoda', 'secondary');
insert into city values ('Maharagama', 'secondary');
insert into city values ('Piliyandala', 'secondary');
insert into city values ('Angoda', 'secondary');
insert into city values ('Athurugiriya', 'secondary');
insert into city values ('Avissawella', 'secondary');
insert into city values ('Battaramulla', 'secondary');
insert into city values ('Boralesgamuwa', 'secondary');
insert into city values ('Hanwella', 'secondary');
insert into city values ('Homagama', 'secondary');
insert into city values ('Kaduwela', 'secondary');
insert into city values ('Kesbewa', 'secondary');
insert into city values ('Kohuwala', 'secondary');
insert into city values ('Kolonnawa', 'secondary');
insert into city values ('Kottawa', 'secondary');
insert into city values ('Kotte', 'secondary');
insert into city values ('Malabe', 'secondary');
insert into city values ('Moratuwa', 'secondary');
insert into city values ('Mount Lavinia', 'secondary');
insert into city values ('Nawala', 'secondary');
insert into city values ('Padukka', 'secondary');
insert into city values ('Pannipitiya', 'secondary');
insert into city values ('Ratmalana', 'secondary');
insert into city values ('Talawatugoda', 'secondary');
insert into city values ('Wellampitiya', 'secondary');
insert into city values ('Gampaha', 'secondary');
insert into city values ('Negombo', 'secondary');
insert into city values ('Kelaniya', 'secondary');
insert into city values ('Kadawatha', 'secondary');
insert into city values ('Ja-Ela', 'secondary');
insert into city values ('Delgoda', 'secondary');
insert into city values ('Divulapitiya', 'secondary');
insert into city values ('Ganemulla', 'secondary');
insert into city values ('Kandana', 'secondary');
insert into city values ('Katunayake', 'secondary');
insert into city values ('Kiribathgoda', 'secondary');
insert into city values ('Minuwangoda', 'secondary');
insert into city values ('Mirigama', 'secondary');
insert into city values ('Nittambuwa', 'secondary');
insert into city values ('Ragama', 'secondary');
insert into city values ('Veyangoda', 'secondary');
insert into city values ('Wattala', 'secondary');
insert into city values ('Mannar', 'secondary');
