insert into city values ('Ampara', 'main');
insert into city values ('Anuradhapura', 'main');
insert into city values ('Badulla', 'main');
insert into city values ('Batticaloa', 'secondary');
insert into city values ('Colombo', 'main');
insert into city values ('Galle', 'main');
insert into city values ('Gampaha', 'main');
insert into city values ('Hambantota', 'main');
insert into city values ('Jaffna', 'main');
insert into city values ('Kalutara South', 'main');
insert into city values ('Kalutara', 'main');
insert into city values ('Kandy', 'main');
insert into city values ('Kegalle', 'secondary');
insert into city values ('Kilinochchi', 'secondary');
insert into city values ('Kurunegala', 'main');
insert into city values ('Mannar', 'secondary');
insert into city values ('Matale', 'secondary');
insert into city values ('Matara', 'main');
insert into city values ('Monaragala', 'secondary');
insert into city values ('Mullaitivu', 'secondary');
insert into city values ('Nuwara Eliya', 'main');
insert into city values ('Polonnaruwa', 'main');
insert into city values ('Puttalam', 'secondary');
insert into city values ('Ratnapura', 'main');
insert into city values ('Trincomalee', 'main');
insert into city values ('Vavuniya', 'secondary');
